<a href="https://colab.research.google.com/github/meem-5971/ML-Fundamentals/blob/main/ML-Fundamentals/NumpyTricksCX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of numpy array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html


In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 29, 37, 45],
       [28, 76, 72, 76],
       [39,  2, 78,  8],
       [87, 60, 63, 71],
       [ 5, 23, 67, 42],
       [49, 83, 25, 28]])

In [ ]:
np.sort(a) #ascending
np.sort(a)[::-1] #descending

array([99, 94, 93, 88, 77, 75, 64, 63, 61, 58, 40, 39, 34, 20,  3])

In [ ]:
np.sort(b) #row wise sort
np.sort(b,axis=0) #column wise sort
np.sort(b,axis=0)[::-1] #column wise sort descending


array([[99, 68, 79, 93],
       [79, 66, 56, 48],
       [78, 40, 48, 32],
       [58, 40, 35, 32],
       [55, 37, 23, 23],
       [36, 28,  8, 12]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
np.append(a,200)

array([ 93,  61,   3,  20,  34,  77,  40,  99,  58,  63,  94,  75,  39,
        64,  88, 200])

In [ ]:
#2D
np.append(b,np.ones((b.shape[0],1)),axis=1)
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[51.        , 29.        , 37.        , 45.        ,  0.24293838],
       [28.        , 76.        , 72.        , 76.        ,  0.6431643 ],
       [39.        ,  2.        , 78.        ,  8.        ,  0.36148527],
       [87.        , 60.        , 63.        , 71.        ,  0.50386768],
       [ 5.        , 23.        , 67.        , 42.        ,  0.77987653],
       [49.        , 83.        , 25.        , 28.        ,  0.11981021]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis. <br>

works like stacking

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) #add with rows
np.concatenate((c,d),axis=1) #add with columns
#

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array<br>
models prefer to use batches of data instead of single data. This function comes to help in this case

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
a

array([93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

In [ ]:
np.expand_dims(a,axis=0) #shape (1x15)

array([[93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88]])

In [ ]:
np.expand_dims(a,axis=1) #shape (15x1)

array([[93],
       [61],
       [ 3],
       [20],
       [34],
       [77],
       [40],
       [99],
       [58],
       [63],
       [94],
       [75],
       [39],
       [64],
       [88]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  5,  7,  8,  9, 10, 11, 13, 14]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  3, 20, 34,  0, 40,  0,  0,  0,  0,  0, 39,  0,  0])

In [ ]:
#all the even nums are replaced with zero
np.where(a%2==0,0,a)

array([93, 61,  3,  0,  0, 77,  0, 99,  0, 63,  0, 75, 39,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
a

array([93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

In [ ]:
np.argmax(a)

7

In [ ]:
b

array([[51, 29, 37, 45],
       [28, 76, 72, 76],
       [39,  2, 78,  8],
       [87, 60, 63, 71],
       [ 5, 23, 67, 42],
       [49, 83, 25, 28]])

In [ ]:
#2D
np.argmax(b,axis=0) #column wise
np.argmax(b,axis=1) #row wise

array([0, 1, 2, 0, 2, 1])

###np.argmin

In [ ]:
np.argmin(a)

2

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
np.cumsum(a)

array([ 93, 154, 157, 177, 211, 288, 328, 427, 485, 548, 642, 717, 756,
       820, 908])

In [ ]:
np.cumsum(b)
np.cumsum(b,axis=0) #col wise
np.cumsum(b,axis=1) #row wise

array([[ 51,  80, 117, 162],
       [ 28, 104, 176, 252],
       [ 39,  41, 119, 127],
       [ 87, 147, 210, 281],
       [  5,  28,  95, 137],
       [ 49, 132, 157, 185]])

###np.cumprod

In [ ]:
np.cumprod(a)

array([                  93,                 5673,                17019,
                     340380,             11572920,            891114840,
                35644593600,        3528814766400,      204671256451200,
          12894289156425600,  1212063180704006400, -1328981815747278080,
        3509941406984809728,  3275321162513203200, -6919642878190944256])

In [ ]:
np.cumprod(b)
np.cumprod(b,axis=0) #col wise
np.cumprod(b,axis=1) #row wise

array([[      51,     1479,    54723,  2462535],
       [      28,     2128,   153216, 11644416],
       [      39,       78,     6084,    48672],
       [      87,     5220,   328860, 23349060],
       [       5,      115,     7705,   323610],
       [      49,     4067,   101675,  2846900]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
np.percentile(a,50) # 50% values are less than 63

63.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
a

array([93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]) #bins=[x,y]->how many values are inbetween x,y

(array([1, 0, 1, 2, 1, 1, 3, 2, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients. <br>
Ranges from -1 to 1 <br>


https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)
#array([[(s,s).        , (s,ex)],
#      [(ex,s), (ex,ex)        ]])

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.<br>
Searches the array to find for some particular items

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
items=[20,30,77,98,90,50,20,30]
np.isin(a,items) #returns boolean a array with True for found items
a[np.isin(a,items)] #returns the numbers which are found

array([20, 77])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
a

array([93, 61,  3, 20, 34, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

In [ ]:
np.flip(a)

array([88, 64, 39, 75, 94, 63, 58, 99, 40, 77, 34, 20,  3, 61, 93])

In [ ]:
b

array([[51, 29, 37, 45],
       [28, 76, 72, 76],
       [39,  2, 78,  8],
       [87, 60, 63, 71],
       [ 5, 23, 67, 42],
       [49, 83, 25, 28]])

In [ ]:
#2D
np.flip(b) #row flip then col flip
np.flip(b,axis=0) #col flip
np.flip(b,axis=1) #row flip


array([[45, 37, 29, 51],
       [76, 72, 76, 28],
       [ 8, 78,  2, 39],
       [71, 63, 60, 87],
       [42, 67, 23,  5],
       [28, 25, 83, 49]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.
<br>
Edit values

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
#changed the values permanently
np.put(a,[0,4],[420,121]) #np.put(array_name,[no_of_indices],[desired_values])

In [ ]:
a

array([420,  61,   3,  20, 121,  77,  40,  99,  58,  63,  94,  75,  39,
        64,  88])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
np.delete(a,[0,2,4]) #np.delete(array,[no_of_indices])

array([61, 20, 77, 40, 99, 58, 63, 94, 75, 39, 64, 88])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d<br>

Operates same way like the python set functions. Additionally it returns numpy array

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n) #common uncommon both

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n) #common

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m) # the items only exist in 2nd set

array([6, 7])

In [ ]:
np.setxor1d(m,n) #uncommon

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,3)] # checks if 1 exists in m set

array([3])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
np.clip(a,a_min=25,a_max=75) #values between 25 to 50

array([75, 61, 25, 25, 75, 75, 40, 75, 58, 63, 75, 75, 39, 64, 75])