<a href="https://colab.research.google.com/github/meem-5971/ML-Fundamentals/blob/main/ML-Fundamentals/NumpyFundamentalCX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numpy Array Basic

In [ ]:
#1D -> vector
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#2D -> matrix
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D ->Tensor
c=np.array([[[1,2],[3,4]],[[5,6],[7,80]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7 80]]]


In [ ]:
#dtype

m=np.array([1,2,3],dtype=float)
n=np.array([1,2,3],dtype=bool) #non zero values are true
o=np.array([1,2,3],dtype=complex)
print(m,n,o)

[1. 2. 3.] [ True  True  True] [1.+0.j 2.+0.j 3.+0.j]


In [ ]:
#np.arange
print(np.arange(1,30,3)) #prints from 1 to 30 with the interval of 3 after each number

[ 1  4  7 10 13 16 19 22 25 28]


In [ ]:
#reshape
np.arange(1,30,2).reshape(5,3)
#prints the previous nums in 2 rows and 3 columns
#(no of row * no of col) must be equal to the num of elements

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4)) #a matrix of 3 rows and 4 columns making each value 1
np.zeros((3,4)) #a matrix of 3 rows and 4 columns making each value 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4)) #a matrix of 3 rows and 4 columns with random values

array([[0.02020912, 0.62518587, 0.76570008, 0.40660471],
       [0.05447828, 0.33651547, 0.98885267, 0.57220467],
       [0.83799057, 0.30653266, 0.91773699, 0.66444116]])

In [ ]:
#np.linspace // linspace -> linearly spaced
# np.linspace(lower range,upper range, no of nums to be generated)
np.linspace(-10,10,10) #prints 10 values with equal distance values from -10 to 10 with

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(3) #prints a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Array Attributes

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim
a3.ndim #prints the dimension of the array


3

In [ ]:
#shape
a1.shape #prints the shape of the array here 10
a2.shape #prints (3,4) ->3 rows 3 cols
a3.shape #prints (2,2,2) ->2 2D array of 2rows x 2col

#tells how many items in each dimension

(2, 2, 2)

In [ ]:
#size
a3.size #prints the total number of items in the array

8

In [ ]:
#item size
a3.itemsize
#how mach memory is occupied by one item in RAM

8

In [ ]:
#dtype for items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Data Types


In [ ]:
#astype
a3.astype(np.int32) #a3.astype(np.desired_datatype)
#converting a3 datatype from int64 to int32
#it is used to save memory when the data is small but assigned datatype holds unneccsary more memory

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operation

scalar operations -> does operations with each elements

In [ ]:
#arithmetic
a1*2 #+,-,*,/,%,**

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#relational
a2>15 #<,>,<=,>=,==,!=

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

vector operations -> when operations between two/more numpy arrays

In [ ]:
#arithmatic
b1=np.arange(10)
b2=np.arange(10)
b3=np.arange(10)
b1+b2+b3

b1**b2**b3

b1 == b2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# Array Functions

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[12., 62., 13.],
       [49., 84., 39.],
       [97., 48., 68.]])

In [ ]:
#max min sum prod
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

491561822029824.0

In [ ]:
 #axis 0 -> col
 #axis 1 -> row
 np.max(a1,axis=0)
 np.prod(a1,axis=1)


array([  9672., 160524., 316608.])

In [ ]:
#mean/median/std/var
np.var(a1,axis=1)

array([544.66666667, 372.22222222, 404.66666667])

In [ ]:
#trigonometric function
np.sin(a1)

array([[-0.53657292, -0.7391807 ,  0.42016704],
       [-0.95375265,  0.73319032,  0.96379539],
       [ 0.37960774, -0.76825466, -0.89792768]])

In [ ]:
#dot product between 2 matrices
#col of 1st matrix == row of 2nd matrix
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log , exponents
np.log(a1)
np.exp(a1)

array([[1.62754791e+05, 8.43835667e+26, 4.42413392e+05],
       [1.90734657e+21, 3.02507732e+36, 8.65934004e+16],
       [1.33833472e+42, 7.01673591e+20, 3.40427605e+29]])

In [ ]:
#round/floor/ceil
np.round(np.random.random((2,3))*100) #nearest integer of float
np.ceil(np.random.random((2,3))*100) #nearest integer greater than float
np.floor(np.random.random((2,3))*100) #nearest integer smaller than float


array([[69., 90., 75.],
       [77., 89., 99.]])

#Indexing and Slicing

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [ ]:
#last item of a1
a1[-1]

9

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#2D
a2[1,2] #[row,col]

6

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#3D
a3[1,0,1] #[no_of_array,row,col]
a3[0,0,0]

0

In [ ]:
#4D [no_of_2D_array,no_of_1D_array,row,col]

In [ ]:
a1[2:5:2] #similar to python list

array([2, 4])

In [ ]:
a2[0,:] #all values of 1st row

array([0, 1, 2, 3])

In [ ]:
a2[:,2] #all values of 3rd col

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

for jumping n cols/rows, add ->  :n at end of slice row/col

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1:2,::3]
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

3d array

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1] #mid 2d array
a3[::2] #1st,last 2D array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#all values of 2nd row of 1st 2D array
a3[0,1:2,:]
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1] #all values of 2nd col of 2nd 2D array

array([10, 13, 16])

In [ ]:
a3[2,1:,1:] #last 2 values of rows and cols of last 2D array

array([[22, 23],
       [25, 26]])

In [ ]:
#1st,last value from 1st row of 1st 2D array and 1st,last value from 1st row of 2nd 2D array
a3[::2,:1,::2]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#2D
for i in a2:
  print(i)
  #prints one row each time

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
#3D
for i in a3:
  print(i)
  #prints 2D array each time


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#print each elements of nD array
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
#reshape (previously discussed)

In [ ]:
#Transpose ->turning rows to col, col to rows
np.transpose(a2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#ravel -> converts any dimensional array to 1D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking -> stacking up 2/more numpy arrays

It is method to combine the data coming from multiple data source

shape must be same for all the input data

In [ ]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#horizontal stacking ->[2x2]stack[2x2] =[2x4] ->no of colum will be added together
np.hstack((a4,a5,a4,a5,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15,
        12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19,
        16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23,
        20, 21, 22, 23]])

In [ ]:
#vertical stacking -> [2x2]stack[2x2]=[4x2] ->no of row will be added together
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Splitting

Opposite of stacking

Has to be equal divisioned

This method might be used to divide data into branches

In [ ]:
#horizontal splitting

np.hsplit(a4,2) #(array_name,no_of_parts_wanted)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
#vertical splitting

np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]