<a href="https://colab.research.google.com/github/meem-5971/ML-Fundamentals/blob/main/Task_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =pd.read_csv("/content/drive/MyDrive/Dataset-20240827T051357Z-001/Dataset/train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

Dropping Unneccessary columns

In [ ]:
train_1=df.copy()

In [ ]:
train_1=train_1.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
train_1

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

Finding the categories of string type data

In [ ]:
pd.unique(train_1['Sex'])

array(['male', 'female'], dtype=object)

In [ ]:
pd.unique(df['Cabin'])

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [ ]:
pd.unique(train_1['Embarked'])

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
pd.unique(train_1['Age'])

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

Finding the missing values

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Replacing the missing values of "Embarked" with Mode

In [ ]:
train_1["Embarked"].fillna(df['Embarked'].mode()[0],inplace=True)
train_1.isnull().sum()

<ipython-input-44-3b6748f6c53c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_1["Embarked"].fillna(df['Embarked'].mode()[0],inplace=True)


Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

Replacing the missing value of Age with Median

In [ ]:
train_1["Age"].fillna(df['Age'].median(),inplace=True)
train_1.isnull().sum()

<ipython-input-45-0b7790e1133f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_1["Age"].fillna(df['Age'].median(),inplace=True)


Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

Encoding the string data

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()
train_1["Sex"]=lb.fit_transform(train_1["Sex"])
train_1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    1  22.0      1      0   7.2500        S
1           1       1    0  38.0      1      0  71.2833        C
2           1       3    0  26.0      0      0   7.9250        S
3           1       1    0  35.0      1      0  53.1000        S
4           0       3    1  35.0      0      0   8.0500        S
..        ...     ...  ...   ...    ...    ...      ...      ...
886         0       2    1  27.0      0      0  13.0000        S
887         1       1    0  19.0      0      0  30.0000        S
888         0       3    0  28.0      1      2  23.4500        S
889         1       1    1  26.0      0      0  30.0000        C
890         0       3    1  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(sparse_output=False, handle_unknown='error',drop='first')



In [ ]:
dfn=oh.fit_transform(train_1[["Embarked"]])
dfn

array([[0., 1.],
       [0., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [ ]:
ohendef=pd.DataFrame(dfn)
ohendef

0    1
0    0.0  1.0
1    0.0  0.0
2    0.0  1.0
3    0.0  1.0
4    0.0  1.0
..   ...  ...
886  0.0  1.0
887  0.0  1.0
888  0.0  1.0
889  0.0  0.0
890  1.0  0.0

[891 rows x 2 columns]

In [ ]:
train_1=train_1.drop(["Embarked"],axis=1)
train_1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    1  22.0      1      0   7.2500
1           1       1    0  38.0      1      0  71.2833
2           1       3    0  26.0      0      0   7.9250
3           1       1    0  35.0      1      0  53.1000
4           0       3    1  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
886         0       2    1  27.0      0      0  13.0000
887         1       1    0  19.0      0      0  30.0000
888         0       3    0  28.0      1      2  23.4500
889         1       1    1  26.0      0      0  30.0000
890         0       3    1  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
train_1=train_1.join(ohendef)
train_1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare    0    1
0           0       3    1  22.0      1      0   7.2500  0.0  1.0
1           1       1    0  38.0      1      0  71.2833  0.0  0.0
2           1       3    0  26.0      0      0   7.9250  0.0  1.0
3           1       1    0  35.0      1      0  53.1000  0.0  1.0
4           0       3    1  35.0      0      0   8.0500  0.0  1.0
..        ...     ...  ...   ...    ...    ...      ...  ...  ...
886         0       2    1  27.0      0      0  13.0000  0.0  1.0
887         1       1    0  19.0      0      0  30.0000  0.0  1.0
888         0       3    0  28.0      1      2  23.4500  0.0  1.0
889         1       1    1  26.0      0      0  30.0000  0.0  0.0
890         0       3    1  32.0      0      0   7.7500  1.0  0.0

[891 rows x 9 columns]

Feature Selection

In [ ]:
x=train_1.drop('Survived',axis=1)
x

Pclass  Sex   Age  SibSp  Parch     Fare    0    1
0         3    1  22.0      1      0   7.2500  0.0  1.0
1         1    0  38.0      1      0  71.2833  0.0  0.0
2         3    0  26.0      0      0   7.9250  0.0  1.0
3         1    0  35.0      1      0  53.1000  0.0  1.0
4         3    1  35.0      0      0   8.0500  0.0  1.0
..      ...  ...   ...    ...    ...      ...  ...  ...
886       2    1  27.0      0      0  13.0000  0.0  1.0
887       1    0  19.0      0      0  30.0000  0.0  1.0
888       3    0  28.0      1      2  23.4500  0.0  1.0
889       1    1  26.0      0      0  30.0000  0.0  0.0
890       3    1  32.0      0      0   7.7500  1.0  0.0

[891 rows x 8 columns]

In [ ]:
y=train_1['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [ ]:
x.columns = x.columns.astype(str)
fit_features=SelectKBest(score_func=f_classif)
fit_features.fit(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_selection/_univariate_selection.py:776: UserWarning: k=10 is greater than n_features=8. All the features will be returned.
  warnings.warn(


SelectKBest()

In [ ]:
fs= pd.DataFrame(fit_features.scores_,index=x.columns,columns=['score value'])
fs

score value
Pclass   115.031272
Sex      372.405724
Age        3.761528
SibSp      1.110572
Parch      5.963464
Fare      63.030764
0          0.011846
1         20.374460

In [ ]:
sp=fs.nlargest(8,'score value')
sp

score value
Sex      372.405724
Pclass   115.031272
Fare      63.030764
1         20.374460
Parch      5.963464
Age        3.761528
SibSp      1.110572
0          0.011846

#Model Fitting

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
y_test

827    1
39     1
820    1
341    1
729    0
      ..
113    0
55     1
204    1
596    1
435    1
Name: Survived, Length: 179, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lrg=LinearRegression()

In [ ]:
lrg.fit(x_train,y_train)

lrg.score(x_train,y_train)*100

43.303115593575455

In [ ]:
lrg.score(x_test,y_test)*100

25.045907473976392

In [ ]:
y_pred_lrg=lrg.predict(x_test)
y_pred_lrg

array([ 4.31849859e-01,  7.26596136e-01,  7.79951959e-01,  8.55280537e-01,
        5.96307540e-01,  1.71103977e-01,  1.01340882e-01,  2.86682808e-01,
        3.51917914e-01,  1.29331393e-01,  1.21028696e-01,  3.08042701e-01,
        1.35123655e-01,  8.67101495e-01,  7.21460942e-01,  4.50746921e-02,
        3.60614604e-01,  7.32377369e-02,  4.44566509e-01,  3.20130838e-01,
        6.95332338e-01,  7.89173646e-02,  3.11173631e-01,  4.17409891e-01,
        8.26793275e-01,  5.08206851e-01,  9.91714937e-01,  5.07536819e-01,
        4.50793306e-01,  5.24149956e-01,  1.35434739e-01,  4.29009946e-01,
        5.43319489e-01, -8.42525089e-02,  3.33110562e-01, -1.55925901e-02,
        1.59072869e-01,  1.06903055e+00,  8.48454950e-02,  3.21282844e-01,
        8.86986662e-01,  7.48658040e-01,  8.06613089e-01,  3.05487866e-01,
        6.92069525e-01,  3.00768740e-01,  6.79359086e-01,  1.39017229e-01,
        8.99869899e-02,  8.68337959e-02,  6.93410659e-01,  4.41348396e-01,
        9.59106579e-02,  